In [4]:
import zarr
import numpy as np
import os
from zarr.storage import ZipStore
from pathlib import Path

src = zarr.open("next1_tokens_AAPL_2025-12-17_first228527.zarr", mode="r")
print(src)

print(src[:])

"""
X = 228527

src = zarr.open("next1_tokens_AAPL_2025-12-17.zarr", mode="r")
slc = src[:X, :]  # reads only first X rows

dst_path = f"next1_tokens_AAPL_2025-12-17_first{X}.zarr"

dst = zarr.open(
    dst_path,
    mode="w",
    shape=(X, src.shape[1]),
    chunks=src.chunks,          # keep same chunking
    dtype=src.dtype,
    compressor=src.compressor,  # keep same compression (if any)
    filters=src.filters         # keep same filters (if any)
)

dst[:] = slc
"""




<zarr.core.Array (228527, 64) int32 read-only>
[[6679  824 8115 ... 1644 5459 4677]
 [6679  824 8115 ... 1644 5459 4677]
 [6679  824 8115 ... 1644 5459 4677]
 ...
 [8115 6931 8115 ... 8115 1644 5459]
 [8115 6931 8115 ... 8115 1644 5459]
 [8115 6931 8115 ... 8115 1644 5459]]


'\nX = 228527\n\nsrc = zarr.open("next1_tokens_AAPL_2025-12-17.zarr", mode="r")\nslc = src[:X, :]  # reads only first X rows\n\ndst_path = f"next1_tokens_AAPL_2025-12-17_first{X}.zarr"\n\ndst = zarr.open(\n    dst_path,\n    mode="w",\n    shape=(X, src.shape[1]),\n    chunks=src.chunks,          # keep same chunking\n    dtype=src.dtype,\n    compressor=src.compressor,  # keep same compression (if any)\n    filters=src.filters         # keep same filters (if any)\n)\n\ndst[:] = slc\n'